In [1]:
import numpy as np

1. Represent the above data in a 10x2 array. In each row, the first element should contain day number and second element should contain steps walked.

In [23]:
Steps1 = np.array ([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

Steps1

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

2. Lee notices that the tracker’s battery dies every day at 7 pm. Lee discovers that on an average, he walks 2000 steps every day after 7 pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.

In [27]:
Steps = np.array ([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

Steps= Steps +[0,2000]
Steps

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

3. Write a program that returns the steps walked if the steps walked are more than 9000.

In [31]:
Steps = np.array ([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
a=Steps > 9000
Steps[a]

array([9569])

In [33]:
print(np.sort(Steps))

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
