In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder , StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression


In [3]:
df = pd.read_csv('Dataset/titanic.csv')
df.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1       0.0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [3]:
df.drop(columns=['PassengerId' , 'Name' , 'Ticket' , 'Fare' , 'Cabin'],inplace=True )

In [4]:
df.fillna(method='ffill'  , inplace=True)

In [5]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [6]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         0.0       1  female  38.0      1      0        C
2         0.0       3  female  38.0      0      0        S
3         0.0       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female  19.0      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [7]:
x= df.iloc[:,1:]

In [8]:
y = df.iloc[:,0]

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [10]:
x_train

Pclass     Sex   Age  SibSp  Parch Embarked
30        1    male  40.0      0      0        C
10        3  female   4.0      1      1        S
873       3    male  47.0      0      0        S
182       3    male   9.0      4      2        S
876       3    male  20.0      0      0        S
..      ...     ...   ...    ...    ...      ...
534       3  female  30.0      0      0        S
584       3    male  36.0      0      0        C
493       1    male  71.0      0      0        C
527       1    male  50.0      0      0        S
168       1    male  45.0      0      0        S

[712 rows x 6 columns]

In [11]:
x_test

Pclass     Sex   Age  SibSp  Parch Embarked
707       1    male  42.0      0      0        S
37        3    male  21.0      0      0        S
615       2  female  24.0      1      2        S
169       3    male  28.0      0      0        S
68        3  female  17.0      4      2        S
..      ...     ...   ...    ...    ...      ...
89        3    male  24.0      0      0        S
80        3    male  22.0      0      0        S
846       3    male  42.0      8      2        S
870       3    male  26.0      0      0        S
251       3  female  29.0      1      1        S

[179 rows x 6 columns]

In [12]:
y_train

30     0.0
10     1.0
873    0.0
182    0.0
876    0.0
      ... 
534    0.0
584    0.0
493    0.0
527    0.0
168    0.0
Name: Survived, Length: 712, dtype: float64

In [13]:
y_test

707    1.0
37     0.0
615    1.0
169    0.0
68     1.0
      ... 
89     0.0
80     0.0
846    0.0
870    0.0
251    0.0
Name: Survived, Length: 179, dtype: float64

In [14]:
tr= ColumnTransformer(transformers=[
    ('tr1',OneHotEncoder(),['Sex' , 'Embarked'])
],remainder='passthrough')

In [15]:
a = tr.fit_transform(x_train)
a

array([[ 0.,  1.,  1., ..., 40.,  0.,  0.],
       [ 1.,  0.,  0., ...,  4.,  1.,  1.],
       [ 0.,  1.,  0., ..., 47.,  0.,  0.],
       ...,
       [ 0.,  1.,  1., ..., 71.,  0.,  0.],
       [ 0.,  1.,  0., ..., 50.,  0.,  0.],
       [ 0.,  1.,  0., ..., 45.,  0.,  0.]])

In [16]:
b =tr.fit_transform(x_test)
b

array([[ 0.,  1.,  0., ..., 42.,  0.,  0.],
       [ 0.,  1.,  0., ..., 21.,  0.,  0.],
       [ 1.,  0.,  0., ..., 24.,  1.,  2.],
       ...,
       [ 0.,  1.,  0., ..., 42.,  8.,  2.],
       [ 0.,  1.,  0., ..., 26.,  0.,  0.],
       [ 1.,  0.,  0., ..., 29.,  1.,  1.]])

In [17]:
log = LogisticRegression(random_state=0)

In [18]:
log.fit(a,y_train)

C:\Users\CS-L2-PC13\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [19]:
y_pred= log.predict(b)
y_pred

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [21]:
print ('Accuracy matrix  = ', accuracy_score(y_test , y_pred))

Accuracy matrix  =  0.7821229050279329


In [22]:
pd.DataFrame(confusion_matrix(y_test , y_pred))

0   1
0  91   9
1  30  49