In [245]:
import numpy as np
import pandas as pd

In [246]:
df = pd.read_csv('Dataset/titanic.csv')
df.head()



PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [248]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  887.000000  891.000000  713.000000  891.000000   
mean    446.000000    0.382187    2.308642   29.704306    0.523008   
std     257.353842    0.486196    0.836071   14.536033    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  888.000000  
mean     0.381594   32.282530  
std      0.806057   49.758986  
min      0.000000    0.000000  
25%      0.000000    7.917700  
50%      0.000000   14.456250  
75%      0.000000   31.068750  
max      6.000000  512.329200

In [249]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [250]:
df.drop(['PassengerId' , 'Ticket' , 'Fare' , 'Cabin', 'Name'],inplace = True,axis=1)
df


Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         NaN       1  female  38.0      1      0        C
2         NaN       3  female   NaN      0      0        S
3         NaN       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female   NaN      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [251]:
df['Survived'].fillna(method = 'ffill' , inplace = True)

In [252]:
df['Age'].fillna(method = 'ffill' , inplace = True)

In [253]:
df['Embarked'].fillna(method = 'ffill' , inplace = True)

In [254]:
x = df.iloc[:,1:]
x

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  38.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female  19.0      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [255]:
y = df.iloc[:,0]
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [256]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    float64
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [257]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
tr = ColumnTransformer(transformers=[
    ('t2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked'])
] , remainder='passthrough')

In [258]:
x1 = tr.fit_transform(x)
x1

array([[ 1.,  0.,  1., ..., 22.,  1.,  0.],
       [ 0.,  0.,  0., ..., 38.,  1.,  0.],
       [ 0.,  0.,  1., ..., 38.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ..., 19.,  1.,  2.],
       [ 1.,  0.,  0., ..., 26.,  0.,  0.],
       [ 1.,  1.,  0., ..., 32.,  0.,  0.]])

In [259]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test=train_test_split(x1,y,train_size=0.2,random_state=2)

In [260]:
x_train

array([[ 0. ,  1. ,  0. , ..., 32. ,  1. ,  1. ],
       [ 1. ,  0. ,  0. , ..., 32.5,  1. ,  0. ],
       [ 0. ,  0. ,  1. , ...,  4. ,  1. ,  1. ],
       ...,
       [ 1. ,  0. ,  0. , ..., 71. ,  0. ,  0. ],
       [ 1. ,  0. ,  1. , ..., 50. ,  0. ,  0. ],
       [ 1. ,  0. ,  1. , ..., 45. ,  0. ,  0. ]])

In [261]:
x_test

array([[ 1.,  0.,  1., ..., 42.,  0.,  0.],
       [ 1.,  0.,  1., ..., 21.,  0.,  0.],
       [ 0.,  0.,  1., ..., 24.,  1.,  2.],
       ...,
       [ 0.,  0.,  1., ..., 44.,  0.,  0.],
       [ 1.,  0.,  1., ..., 28.,  0.,  0.],
       [ 1.,  1.,  0., ..., 21.,  0.,  0.]])

In [262]:
y_train

657    0.0
122    0.0
750    1.0
841    0.0
361    0.0
      ... 
534    0.0
584    0.0
493    0.0
527    0.0
168    0.0
Name: Survived, Length: 178, dtype: float64

In [263]:
y_test

707    1.0
37     0.0
615    1.0
169    0.0
68     1.0
      ... 
298    1.0
290    1.0
415    0.0
313    0.0
421    0.0
Name: Survived, Length: 713, dtype: float64

In [264]:
from sklearn.tree import DecisionTreeClassifier

In [265]:
dtc = DecisionTreeClassifier()

In [266]:
dtc

DecisionTreeClassifier()

In [269]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [270]:
y_pred=dtc.predict(x_test)
y_pred

array([0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 1.

In [271]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [272]:
print ('Accuracy matrix  = ', accuracy_score(y_test , y_pred))

Accuracy matrix  =  0.7349228611500701


In [273]:
pd.DataFrame(confusion_matrix(y_test , y_pred))

0    1
0  349   91
1   98  175